# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/eecc2d02-4fd6-4825-9a64-9b7c342e7ab6";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/hdd/hdd-256gb" =
    { device = "/dev/disk/by-uuid/82f977ad-b383-4f69-80c7-1977fd4ae873";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/115C-8F68";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/hdd/hdd-1tb" =
    { device = "/dev/disk/by-uuid/9f2ce4c2-7d56-4ee4-ad5f-57d3a5b84c09";
      fsType = "btrfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5e76e18c-fc75-46cf-b30d-8c3a318ee9e1"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # NVIDIA proprietäre Treiber hinzufügen
  services.xserver.videoDrivers = [ "nvidia" ]; # Aktiviert den NVIDIA-Treiber
  hardware.nvidia.modesetting.enable = true;    # Aktiviert Modesetting für NVIDIA
  hardware.nvidia.package = pkgs.nvidiaPackages.latest; # Verwendet den neuesten Treiber
}
